name: Deploy to GitHub Pages

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'deploy-docs')
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /ibex-user-docs

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      # - name: Install Dependencies
      #   run: npm install style-dictionary token-transformer

      # - name: Run token-transformer
      #   run: npx token-transformer sd-input/src/from-figma-tokens.json sd-input/src/sd-input.json --resolveReferences false

      # - name: Run Style-Dictionary
      #   run: npx style-dictionary build --config sd.config.cjs

      # - name: Commit Changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: ${{ github.actor }}
      #     author_email: ${{ github.actor }}@users.noreply.github.com
      #     message: 'Tokens Updated - publish-to-npm branch'
      #     add: '.'
      - name: Get files
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Export static files
        run: npm run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
